refactoring #42 - global structural refactoring
winniepukki/trinat pull request #43
Opened 2021-06-11 15:14 UTC by winniepukki

Fixes: winniepukki/trinat#42

2021-06-12 15:31 UTC, elinapeshelee requested changes
Please pay attention to the improvement tips ♥️

2021-06-12 15:31 UTC, elinapeshelee commented on src/public/manifest.json
> +    },
Please provide the code with the `apple-touch-icon`

2021-06-12 15:31 UTC, elinapeshelee commented on webpack.config.js
>              ]
This should be destructured from the `paths` variables from above in the future

2021-06-12 15:31 UTC, elinapeshelee commented on webpack.config.js
>          new CopyWebpackPlugin({
The `alias: {}` object lacks the `@type` directory. This should be provided

2021-06-12 19:00 UTC, winniepukki commented on webpack.config.js
>          new CopyWebpackPlugin({
Good tips. Thank you! 😊

2021-06-14 09:29 UTC, winniepukki commented on webpack.config.js
>              ]
This is a great tip that will be taken into the consideration in the upcoming PR!!

2021-06-14 09:44 UTC, elinapeshelee approved these changes
Looks legit

2021-06-14 09:45 UTC, merged