1.1.0 rc
winniepukki/trinat pull request #50
Opened 2021-06-19 07:56 UTC by winniepukki

Fixes #45 
Release version 1.1.0 candidate branch

2021-06-20 18:33 UTC, elinapeshelee requested changes
Please mind the comments

2021-06-20 18:33 UTC, elinapeshelee commented on src/app/component/Loading/Loading.component.js
> +                    />
I am sure there are ways to avoid such `svg` file usage. Did you investigate?

2021-06-20 18:33 UTC, elinapeshelee commented on src/app/query/ProductList.query.js
> +/* eslint-disable no-return-await */
Please ensure there are no `eslint-disable` rules. Perhaps, this bug can be reported to the `Winniepukki-guardian` package

2021-06-20 18:35 UTC, winniepukki commented on src/app/component/Loading/Loading.component.js
> +                    />
Currently under the investigation

2021-06-20 18:35 UTC, winniepukki commented on src/app/query/ProductList.query.js
> +/* eslint-disable no-return-await */
Thanks for noting that. Will take into the consideration

2021-06-22 13:15 UTC, winniepukki reviewed
Please be aware of those notes

2021-06-22 13:15 UTC, winniepukki commented on src/public/index.html
> +    <meta name="theme-color" content="#cfa670">
Description and keywords are planned after receiving the `lv` locale from the business owners

2021-06-25 16:46 UTC, winniepukki commented
Running the smoke tests

2021-06-25 17:10 UTC, elinapeshelee approved these changes
Smoke passed. Please ensure you have adjusted the AWS Amplify runner on its' end

2021-06-25 17:12 UTC, merged